// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TerrainShaderThreeKeys
    {
        public static readonly ValueParameterKey<float> TextureRepeat = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ObjectParameterKey<Texture> FirstWeights = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> SecondWeights = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_4 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_5 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_6 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_7 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_8 = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector4> Viewport = ParameterKeys.NewValue<Vector4>();
    }
}
