// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TerrainHeightShaderKeys
    {
        public static readonly ValueParameterKey<int> TextureRepeat = ParameterKeys.NewValue<int>(1);
        public static readonly ValueParameterKey<Vector2> HeightRange = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> SlopeCutoff = ParameterKeys.NewValue<float>(0.2f);
        public static readonly ValueParameterKey<float> DistanceMultiplier = ParameterKeys.NewValue<float>(10.0f);
        public static readonly ValueParameterKey<float> DetailMappingDistance = ParameterKeys.NewValue<float>(100.0f);
        public static readonly ValueParameterKey<float> HeightLevels = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Texture> HeightMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BumpMap_1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BumpMap_2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> SlopeTex_1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> SlopeTex_2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> DetailTex = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_4 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_5 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_6 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_7 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_8 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_9 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Texture_10 = ParameterKeys.NewObject<Texture>();
    }
}
